var authorTag = "###Script analysis generated by RevScriptor###";
var generatedScript = "";
var dataOptions = "filepath";
//var num_char_states = 4;
var substitutionmodelTag = "";
var substitutionmodelTag = "";
var substitutionModel= "";
var treeTag = "";
var treeModel = "";
var mcmcTag = "";
var mcmc = "";

//This default code before substitution options
var variables = "# Get some useful variables from the data. We need these later on.\n" +
                 "num_taxa <- data.ntaxa()\n" +
                 "num_branches <- 2 * num_taxa - 3\n" +
                 "taxa <- data.taxa()\n\n"+
                 "moves    = VectorMoves()\n" +
                 "monitors = VectorMonitors()\n\n" +
                 "num_char_states <- 4";

//Makes a RevBayes Title Tag with the given string
function revbayesTag(word){
    var tempword ="# " + word + " #";
    var temp = "";
    var i;
    for(i = 0; i < word.length + 4; i++){
        temp = temp + "#";
    }

    var words = [temp, tempword, temp];
    return word = words.join('\n');
}

//creates the script that will be generated.
function createScript(){
    dataoptions = getdataOptions();
    substitutionmodelTag = revbayesTag("Substitution Model");
    substitutionModel = getSubstitutionOptions();
    treeTag = revbayesTag("Tree Model");
    treeModel = getTreeOptions();
    mcmcTag = revbayesTag("MCMC");
    mcmc = getMCMCOptions();
    var scripts = [authorTag, dataoptions, variables, substitutionmodelTag, substitutionModel, treeTag, treeModel, mcmcTag, mcmc];
   
    //Checks to see if there are any missing inputs that the user needs to choose from
    if(!dataoptions){
        generatedScript = "Missing inputs in the DATA options.";
        alert("Missing inputs in the DATA options.");
    }
    else if(!substitutionModel){
        generatedScript = "Missing inputs in the Substitution Model options.";
        alert("Missing inputs in the Substitution Model options.");
    }
    else if(!treeModel){
        generatedScript = "Missing inputs in the Tree Model options.";
        alert("Missing inputs in the Tree Model options.");
    }
    else if(!mcmc){
        generatedScript = "Missing inputs in the MCMC options.";
        alert("Missing inputs in the MCMC options.");
    }
    else{
        generatedScript = scripts.join('\n\n');
    }

}

//Resets the script
function resetScript(){
    generatedScript = "";
    document.getElementById('myTextarea').value = "Example script.....";
}

//Puts the script into the text area
function generateScript(){
	createScript();
    document.getElementById('myTextarea').value = generatedScript; 
}